[project]
name = "traffic-flow-analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka[avro]>=2.15.0",
    "fastapi>=0.141.1",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "ultralytics>=8.4.116",
    "uvicorn>=0.52.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
